platform :ios, '13.0'

# pod 'Firebase/Analytics'
# pod 'Firebase/Messaging'
# pod 'Firebase/Crashlytics'
pod 'FirebaseAnalytics'
pod 'FirebaseMessaging'
pod 'FirebaseCrashlytics'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
